#!/bin/bash

# thanks to https://stackoverflow.com/questions/22009364/is-there-a-try-catch-command-in-bash for this "try/catch" code
{
    npm run lint
} || {
  exit 1
}

{
    npm run test
} || {
  exit 1
}

exec 1>&2
exec < /dev/tty

consoleregexp='^\+.*console\.log('
debuggerregexp='debugger'
if test $(git diff --cached | grep $consoleregexp | wc -l) != 0
then
  exec git diff --cached | grep -ne $consoleregexp
  read -p 'You have added one or more console logs in your modification. Are you sure want to continue? (y/n)' yn
  echo $yn | grep ^[Yy]$
  if [ $? -eq 0 ]
  then
    exit 0;
  else
    exit 1;
  fi
fi
if test $(git diff --cached | grep $debuggerregexp | wc -l) != 0
then
  exec git diff --cached | grep -ne $debuggerregexp
  read -p 'You have added one or more debuggers in your modification. Are you sure want to continue? (y/n)' yn
  echo $yn | grep ^[Yy]$
  if [ $? -eq 0 ]
  then
    exit 0;
  else
    exit 1;
  fi
fi
