#!/bin/sh

function resetAndExit()
{
  git reset HEAD . && exit 1;
}

# check if user is trying to push up to a branch they may not want to
function checkBranches()
{
if test $(git rev-parse --abbrev-ref HEAD | grep -c $1) != 0; then
  read -p "Warning: you are trying to push to $1. Continue? y/n" yn
  echo $yn | grep ^[Yy]$
  if [ $? -eq 0 ]
  then
    echo 'Ok, continuing.';
  else
    resetAndExit
  fi
fi
}

warningBranches=('^exp' '^master$' '^develop$')

for i in "${warningBranches[@]}"
do
  checkBranches "$i"
done


