#!/bin/bash

exec 1>&2
exec < /dev/tty

consoleregexp='^\+.*Log\.d('
if test $(git diff --cached | grep $consoleregexp | wc -l) != 0
then
  exec git diff --cached | grep -ne $consoleregexp
  read -p 'You have added one or more console logs in your modification. Are you sure want to continue? (y/n)' yn
  echo $yn | grep ^[Yy]$
  if [ $? -eq 0 ]
  then
    exit 0;
  else
    exit 1;
  fi
fi
